language: node_js

node_js:
  - 'stable'
  - '8'
  - '6'

sudo: false

env:
  - workerCount=3

matrix:
  fast_finish: true

branches:
  only:
  - master
  - release-2.5
  - release-2.6
  - release-2.7

install:
  - npm uninstall typescript --no-save
  - npm uninstall tslint --no-save
  - npm install
  - if [ "$TRAVIS_NODE_VERSION" = "6" ]; then
      npm uninstall typemock @typescript/vfs @typescript/vfs-path @typescript/vfs-core @typescript/vfs-errors --no-save;
      npm run build:private-packages;
      npm install file:scripts/typemock file:scripts/vfs-errors file:scripts/vfs-core file:scripts/vfs-path file:scripts/vfs --no-save;
    fi

cache:
  directories:
    - node_modules

git:
  depth: 1
